feat: added google-recaptcha verification integration in claim api
AElfProject/faucet-backend pull request #9
Opened 2024-10-23 03:32 UTC by RutvikGhaskataEalf

2024-10-28 07:35 UTC, zhifenglee-aelf requested changes

2024-10-28 07:35 UTC, zhifenglee-aelf commented on src/AELFFaucet.Application/CodeStatus.cs
>          BalanceNotAdequate = 4, //余额不足
Can you please also translate the chinese text to english? Thanks!

2024-10-28 07:35 UTC, zhifenglee-aelf commented on src/AELFFaucet.Application/Project/ClaimService.cs
> +        var url = $"https://www.google.com/recaptcha/api/siteverify?secret={secretKey}&response={recaptchaToken}";
put the link `https://www.google.com/recaptcha/api/siteverify` in appsettings.json

2024-10-28 07:35 UTC, zhifenglee-aelf commented on src/AELFFaucet.Application/Project/ClaimService.cs
> +    public class CaptchaResponse
Create a new file CaptchaResponse.cs for this class.

2024-10-28 07:35 UTC, zhifenglee-aelf commented on src/AELFFaucet.Application/Project/ClaimService.cs
> +        // Verify reCAPTCHA token here based on platform
This code is reused multiple times, create a helper function and reuse the function in other places. This will help to maintain the code better

2024-10-28 07:35 UTC, zhifenglee-aelf commented on src/AELFFaucet.Application/Project/ClaimService.cs
> +
Remove unused code.

2024-10-28 07:35 UTC, zhifenglee-aelf commented on src/AELFFaucet.Application/Project/ClaimService.cs
> +    public async Task<MessageResult> ClaimSeedAsync(string walletAddress, string recaptchaToken, [FromHeader(Name = "Platform")] string platform)
You need to add this new function signature to IClaimService. The same for the rest where you changed function definition.

2024-10-28 07:35 UTC, zhifenglee-aelf commented on src/AELFFaucet.Web/appsettings.json
> +    "NftSeedPrivateKey": "97a1747af1539a6b839c92227c8f5ca90ef0e7de70e5c2f46c64f27b12fabdd7",
All these keys should be removed and instead, for local development, use secrets.json instead.

2024-10-29 03:07 UTC, zhifenglee-aelf commented on src/AELFFaucet.Application/CodeStatus.cs
>          BalanceNotAdequate = 4, //余额不足
Please remove the chinese text. Thanks

2024-10-29 03:12 UTC, zhifenglee-aelf requested changes

2024-10-29 03:12 UTC, zhifenglee-aelf commented on src/AELFFaucet.Application/CodeStatus.cs
> +        Success = 1, //成功 (success)
Remove chinese text. Just the english comment will do

2024-10-29 03:15 UTC, zhifenglee-aelf requested changes

2024-10-29 03:15 UTC, zhifenglee-aelf commented on README.md
> +dotnet user-secrets set "ApiConfig:RecaptchaVerifyUrl" "https://www.google.com/recaptcha/api/siteverify"
This Url don't need to be in secrets.json. This should be in appsettings. Same for ApiConfig:SendCount, ApiConfig:BaseUrlForSidechain, ApiConfig:BaseUrlForMainchain and ApiConfig:BaseUrl. Only put keys into secrets.json. Non-sensitive information should go to appsettings.json

2024-10-29 03:17 UTC, zhifenglee-aelf requested changes

2024-10-29 03:17 UTC, zhifenglee-aelf commented on README.md
> +dotnet user-secrets set "ApiConfig:PrivateKey" "b192e307da4c4e1a00eeed442a4b5e8e0b7b2c6f838d0472627b846e5280c51c"
Also please do not expose keys in README.md. You can have a <insert your private key here> instead of an exact key.

2024-10-29 03:17 UTC, zhifenglee-aelf commented on README.md
> +dotnet user-secrets set "ApiConfig:NftSeedPrivateKey" "97a1747af1539a6b839c92227c8f5ca90ef0e7de70e5c2f46c64f27b12fabdd7"
Same change needed as PrivateKey

2024-10-29 03:36 UTC, zhifenglee-aelf requested changes

2024-10-29 03:43 UTC, RutvikGhaskataEalf commented on README.md
> -  "ApiConfig": {
Yes already added

2024-10-29 05:04 UTC, zhifenglee-aelf approved these changes

2024-10-31 05:34 UTC, merged